### ISSUE TITLE
cant find Uzi and N suits

### ISSUE THREAD

**Issue by Nagatka** [aNaOH/LethalDrones#1]
I checked many times to see if they were on the rack, but they weren't.

**Comment by aNaOH** [comment]
Ok! I checked it out and it seems a problem when downloading from a mod manager (in my case r2modman), looking for a fix and sorry for the inconvenience!

**Comment by aNaOH** [comment]
@Nagatka
Ok! The update should be live soon

The fixed version should be 1.0.5212
